// ALL texts of the interface live here: key → text.
// To switch the interface to German, change UI_LANG to 'de' (the German set is below).
// {name}, {n} … are placeholders that the app fills in.
// The tutor lines (tutor*) are German in both sets: the tutor always speaks German.

export const UI_LANG = 'en';

const tutor = {
  tutorAskName: 'Grüezi! Ich bin wort., dein Deutsch-Sparringspartner. Wie heisst du?',
  tutorNameAgain: 'Wie heisst du? Schreib einfach deinen Vornamen.',
  tutorAskCode: 'Hallo {name}! Wie lautet euer Klassen-Code?',
  tutorBadCode: 'Hmm, dieser Code stimmt leider nicht. Achte auf Gross- und Kleinschreibung und versuch es nochmal.',
  tutorCodeError: 'Ich kann den Code gerade nicht prüfen. Versuch es bitte gleich nochmal.',
  tutorAskTopic: 'Was möchtest du heute üben?',
  tutorHelloTopic: 'Hallo {name}! Was möchtest du heute üben?',
  tutorCodeOk: 'Danke, der Code stimmt! Was möchtest du heute üben?',
  tutorCodeChanged: 'Der Klassen-Code stimmt nicht mehr. Wie lautet euer Klassen-Code?',
  tutorCodeThanks: 'Danke! Schick mir deine letzte Nachricht bitte nochmal.',
  tutorWelcomeBack: 'Willkommen zurück, {name}! Was üben wir heute?',
  tutorLastTime: 'Letztes Mal: {topic} ({score}).',
  tutorResume: 'Willkommen zurück, {name}! Wir machen da weiter, wo du aufgehört hast.',
  tutorAskTopicAgain: 'Gern! Was möchtest du jetzt üben?',
  tutorChooseGrammar: 'Welches Grammatik-Thema möchtest du üben?',
  tutorChooseVocab: 'Welchen Wortschatz möchtest du üben?',
  tutorNoTopicsForLevel: 'Für {level} gibt es noch keine eigenen Lektionen. Hier sind alle Themen – ich passe die Sprache an dein Niveau an.',
  tutorNoTopicsOfType: 'Dazu gibt es noch keine Lektion. Wähle ein anderes Thema oder schreib mir, was du üben möchtest.',
  tutorRestart: 'Neue Runde, {name}! Was möchtest du üben?',
};

const en = {
  ...tutor,
  // header
  brand: 'wort.',
  tagline: 'Your German, one conversation at a time.',
  streak: '{n}-day streak',
  hello: 'Hallo, {name}',
  accountMenu: 'Account menu',
  menuNewSession: 'Start a new session',
  menuChangeName: 'Change name',
  confirmChangeName: 'Start again with a different name? Your progress on this device will be kept.',

  // chat
  chatTitle: "Let's talk German.",
  chatSubtitle: 'Pick a topic, change your level, or ask for help. Just say it here.',
  statusStarting: 'Getting started',
  statusChoosing: 'Choosing a topic',
  statusRoleplay: 'Role-play in progress',
  statusLesson: 'Lesson in progress',
  statusFinished: 'Session complete',
  today: 'Today',
  you: 'You',
  tutorName: 'wort.',
  tutorRole: 'Your German tutor',
  taskOf: 'Task {n} of {total}',
  feedbackSpotOn: 'Spot on',
  feedbackPolish: 'A little polish',
  feedbackFix: "Let's fix this",
  summaryTitle: 'Session complete',
  summaryScore: '{correct} of {answered} correct',
  inputLabel: 'Your message',
  inputPlaceholder: "Reply in German, or tell wort. what you'd like to do …",
  inputPlaceholderName: 'Type your name …',
  inputPlaceholderCode: 'Type the class code …',
  send: 'Send',
  composerNote: 'Your conversation is the control panel. Everything updates as you chat.',
  enterToSend: 'Enter to send ↵',
  typing: 'wort. is writing …',
  typingSlow: 'Still thinking – the tutor is a bit slow right now …',
  retry: 'Try again',
  errorNetwork: 'No connection to the server. Check your internet and try again.',
  errorUnexpected: 'The server sent an unexpected answer ({status}). Please try again.',
  errorTimeout: 'The tutor took too long to answer. Please try again.',
  codeHidden: '••••••',

  // "You can say" panel
  optionsTitle: 'You can say',
  optionsHide: 'Hide options',
  optionsShow: 'Show options',
  optionsTab: 'Options',
  groupNow: 'Right now',
  groupPractising: 'While practising',
  groupTopics: 'Topics for {level}',
  groupTopicsAll: 'All topics',
  groupTopic: 'Topic & theme',
  optionsFootnote: 'Tap one, or just type it in the chat.',
  optionsOnboarding: 'Answer wort. in the chat to get started. The options appear here.',
  chipHint: 'Give me a hint',
  chipRule: 'Explain the rule',
  chipSkip: 'Skip this one',
  chipRepeat: 'Repeat my mistakes',
  chipGrammar: 'Grammar',
  chipVocab: 'Vocabulary',
  chipRoleplay: 'New role-play',
  chipChangeTopic: 'Change topic',
  chipEasier: 'Easier',
  chipHarder: 'Harder',

  // right panel: settings
  panelTitle: 'Your session',
  level: 'Level',
  difficulty: 'Difficulty',
  diff_easy: 'Easy',
  diff_medium: 'Medium',
  diff_hard: 'Hard',
  diffHelp_easy: 'Hints in brackets, multiple choice allowed, short answers.',
  diffHelp_medium: 'A small hint under each task, no case hint.',
  diffHelp_hard: 'No hints. Free answers in full sentences, natural speed.',
  topic: 'Topic',
  theme: 'Theme',
  notChosen: 'Not chosen yet',
  settingsNote: 'Topic and theme are chosen in the chat.',
  type_Grammatik: 'Grammar',
  type_Wortschatz: 'Vocabulary',
  type_Gemischt: 'Mixed',
  type_free: 'Free practice',
  ex_roleplay: 'role-play',
  ex_gapfill: 'gap fill',
  ex_noundrill: 'noun drill',
  ex_translation: 'translation',
  ex_choice: 'multiple choice',
  ex_build: 'sentence building',
  ex_findmistake: 'find the mistake',

  // right panel: views
  views: 'Views',
  view_glance: 'At a glance',
  view_progress: 'Progress & gaps',
  view_grammar: 'Grammar focus',
  panelHint: 'You can also change all of this in the chat, e.g. «make it harder» or «show me the grammar focus».',

  // at a glance
  currentLesson: 'Current lesson',
  synced: 'Synced with chat',
  levelName_A1: 'Beginner',
  levelName_A2: 'Elementary',
  levelName_B1: 'Intermediate',
  levelCaption: 'Your study level · CEFR',
  scenarioLabel: 'Theme / scenario',
  scenarioEmpty: 'Your role-play scene appears here once you pick a topic in the chat.',
  exerciseType: 'Exercise type',
  grammarFocusLine: 'Grammar focus: {rule}',
  howYoureDoing: "How you're doing",
  headline_none: "Let's begin.",
  headline_perfect: 'Perfect so far.',
  headline_strong: 'Going strong.',
  headline_good: 'A good start.',
  headline_keep: 'Keep at it.',
  basedOnOne: 'Based on your last answer',
  basedOnMany: 'Based on your last {n} answers',
  basedOnNone: 'Answer the first task to see your score',
  correctLabel: 'correct',
  onTarget: 'On target',
  keepPractising: 'Keep practising',
  lessonProgress: 'Lesson progress',
  tasksOf: '{n} of {total} tasks',
  recentSessions: 'Last sessions',

  // progress & gaps
  gapTitle: 'Gap from this conversation',
  yourAnswer: 'Your answer',
  corrected: 'Corrected',
  noGapTitle: 'No gaps so far',
  noGapText: 'When something goes wrong, the rule behind it shows up here – with your answer and the correction.',
  yourAnswers: 'Your answers',
  scoreCorrect: '{correct}/{answered} correct',
  youWrote: '(you: {words})',
  noAnswers: 'Every answer you give appears here, with the correction.',

  // grammar focus
  grammarFocus: 'Grammar focus',
  fromConversation: 'From your conversation',
  watchOut: 'Watch out',
  noGrammar: 'The rule of your topic appears here once you start. You can also say «Explain the rule».',

  // short lines in the chat when a button changes something
  sysLevel: 'Level: {value}',
  sysDifficulty: 'Difficulty: {value}',
  sysView: 'View: {value}',
  sysTopic: 'Topic: {value}',
  sysNewSession: 'New session',
};

const de = {
  ...tutor,
  brand: 'wort.',
  tagline: 'Dein Deutsch, ein Gespräch nach dem anderen.',
  streak: '{n} Tage in Folge',
  hello: 'Hallo, {name}',
  accountMenu: 'Konto-Menü',
  menuNewSession: 'Neue Sitzung starten',
  menuChangeName: 'Namen ändern',
  confirmChangeName: 'Mit einem anderen Namen neu beginnen? Dein Fortschritt auf diesem Gerät bleibt gespeichert.',

  chatTitle: 'Lass uns Deutsch reden.',
  chatSubtitle: 'Wähle ein Thema, ändere dein Niveau oder frag nach Hilfe. Schreib es einfach hier.',
  statusStarting: 'Los geht’s',
  statusChoosing: 'Thema wählen',
  statusRoleplay: 'Rollenspiel läuft',
  statusLesson: 'Lektion läuft',
  statusFinished: 'Sitzung beendet',
  today: 'Heute',
  you: 'Du',
  tutorName: 'wort.',
  tutorRole: 'Dein Deutsch-Tutor',
  taskOf: 'Aufgabe {n} von {total}',
  feedbackSpotOn: 'Genau richtig',
  feedbackPolish: 'Ein kleiner Schliff',
  feedbackFix: 'Das korrigieren wir',
  summaryTitle: 'Sitzung beendet',
  summaryScore: '{correct} von {answered} richtig',
  inputLabel: 'Deine Nachricht',
  inputPlaceholder: 'Antworte auf Deutsch oder sag wort., was du machen möchtest …',
  inputPlaceholderName: 'Schreib deinen Namen …',
  inputPlaceholderCode: 'Schreib den Klassen-Code …',
  send: 'Senden',
  composerNote: 'Dein Gespräch ist die Steuerung. Alles passt sich an, während du schreibst.',
  enterToSend: 'Enter zum Senden ↵',
  typing: 'wort. schreibt …',
  typingSlow: 'Einen Moment noch – der Tutor ist gerade etwas langsam …',
  retry: 'Nochmal versuchen',
  errorNetwork: 'Keine Verbindung zum Server. Prüfe dein Internet und versuch es nochmal.',
  errorUnexpected: 'Unerwartete Antwort vom Server ({status}). Bitte versuch es nochmal.',
  errorTimeout: 'Der Tutor hat zu lange gebraucht. Bitte versuch es nochmal.',
  codeHidden: '••••••',

  optionsTitle: 'Du kannst sagen',
  optionsHide: 'Optionen ausblenden',
  optionsShow: 'Optionen einblenden',
  optionsTab: 'Optionen',
  groupNow: 'Gerade jetzt',
  groupPractising: 'Beim Üben',
  groupTopics: 'Themen für {level}',
  groupTopicsAll: 'Alle Themen',
  groupTopic: 'Thema & Szenario',
  optionsFootnote: 'Tippe eine Option an oder schreib sie einfach in den Chat.',
  optionsOnboarding: 'Antworte wort. im Chat, um zu starten. Die Optionen erscheinen hier.',
  chipHint: 'Gib mir einen Tipp',
  chipRule: 'Erklär die Regel',
  chipSkip: 'Überspringen',
  chipRepeat: 'Wiederhole meine Fehler',
  chipGrammar: 'Grammatik',
  chipVocab: 'Wortschatz',
  chipRoleplay: 'Neues Rollenspiel',
  chipChangeTopic: 'Anderes Thema',
  chipEasier: 'Leichter',
  chipHarder: 'Schwieriger',

  panelTitle: 'Deine Sitzung',
  level: 'Niveau',
  difficulty: 'Schwierigkeit',
  diff_easy: 'Leicht',
  diff_medium: 'Mittel',
  diff_hard: 'Schwer',
  diffHelp_easy: 'Tipps in Klammern, Auswahlantworten erlaubt, kurze Antworten.',
  diffHelp_medium: 'Ein kleiner Tipp unter jeder Aufgabe, kein Hinweis auf den Kasus.',
  diffHelp_hard: 'Keine Tipps. Freie Antworten in ganzen Sätzen, natürliches Tempo.',
  topic: 'Thema',
  theme: 'Szenario',
  notChosen: 'Noch nicht gewählt',
  settingsNote: 'Thema und Szenario wählst du im Chat.',
  type_Grammatik: 'Grammatik',
  type_Wortschatz: 'Wortschatz',
  type_Gemischt: 'Gemischt',
  type_free: 'Freies Üben',
  ex_roleplay: 'Rollenspiel',
  ex_gapfill: 'Lückentext',
  ex_noundrill: 'Nomen-Drill',
  ex_translation: 'Übersetzung',
  ex_choice: 'Auswahl',
  ex_build: 'Satzbau',
  ex_findmistake: 'Fehler finden',

  views: 'Ansichten',
  view_glance: 'Überblick',
  view_progress: 'Fortschritt & Lücken',
  view_grammar: 'Grammatik-Fokus',
  panelHint: 'Du kannst all das auch im Chat ändern, z. B. «schwieriger» oder «zeig mir den Grammatik-Fokus».',

  currentLesson: 'Aktuelle Lektion',
  synced: 'Mit dem Chat verbunden',
  levelName_A1: 'Anfänger',
  levelName_A2: 'Grundstufe',
  levelName_B1: 'Mittelstufe',
  levelCaption: 'Dein Niveau · GER',
  scenarioLabel: 'Thema / Szenario',
  scenarioEmpty: 'Deine Rollenspiel-Szene erscheint hier, sobald du im Chat ein Thema wählst.',
  exerciseType: 'Übungsform',
  grammarFocusLine: 'Grammatik-Fokus: {rule}',
  howYoureDoing: 'So läuft es',
  headline_none: 'Los geht’s.',
  headline_perfect: 'Bisher perfekt.',
  headline_strong: 'Sehr stark.',
  headline_good: 'Ein guter Anfang.',
  headline_keep: 'Dranbleiben!',
  basedOnOne: 'Nach deiner letzten Antwort',
  basedOnMany: 'Nach deinen letzten {n} Antworten',
  basedOnNone: 'Beantworte die erste Aufgabe, dann siehst du dein Ergebnis',
  correctLabel: 'richtig',
  onTarget: 'Sitzt',
  keepPractising: 'Weiter üben',
  lessonProgress: 'Fortschritt der Lektion',
  tasksOf: '{n} von {total} Aufgaben',
  recentSessions: 'Letzte Sitzungen',

  gapTitle: 'Lücke aus diesem Gespräch',
  yourAnswer: 'Deine Antwort',
  corrected: 'Korrigiert',
  noGapTitle: 'Bisher keine Lücken',
  noGapText: 'Wenn etwas nicht stimmt, erscheint hier die Regel dazu – mit deiner Antwort und der Korrektur.',
  yourAnswers: 'Deine Antworten',
  scoreCorrect: '{correct}/{answered} richtig',
  youWrote: '(du: {words})',
  noAnswers: 'Jede Antwort erscheint hier, mit der Korrektur.',

  grammarFocus: 'Grammatik-Fokus',
  fromConversation: 'Aus deinem Gespräch',
  watchOut: 'Achtung',
  noGrammar: 'Die Regel deines Themas erscheint hier, sobald du startest. Du kannst auch «Erklär die Regel» sagen.',

  sysLevel: 'Niveau: {value}',
  sysDifficulty: 'Schwierigkeit: {value}',
  sysView: 'Ansicht: {value}',
  sysTopic: 'Thema: {value}',
  sysNewSession: 'Neue Sitzung',
};

const SETS = { en, de };

export function t(key, vars) {
  const text = SETS[UI_LANG]?.[key] ?? en[key] ?? key;
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (vars[k] ?? m));
}
