// ALL texts of the interface live here: key → text.
// To switch the interface to German, change UI_LANG to 'de' (the German set is below).
// {name}, {n} … are placeholders that the app fills in.
// The tutor lines (tutor*) are German in both sets: the tutor always speaks German.

export const UI_LANG = 'en';
export const LOCALE = { en: 'en-GB', de: 'de-CH' }[UI_LANG]; // for dates and times

const tutor = {
  tutorAskName: 'Grüezi! Ich bin wort., dein Deutsch-Sparringspartner. Wie heisst du?',
  tutorNameAgain: 'Wie heisst du? Schreib einfach deinen Vornamen.',
  tutorAskCode: 'Hallo {name}! Wie lautet euer Klassen-Code?',
  tutorBadCode: 'Hmm, dieser Code stimmt leider nicht. Achte auf Gross- und Kleinschreibung und versuch es nochmal.',
  tutorCodeError: 'Ich kann den Code gerade nicht prüfen. Versuch es bitte gleich nochmal.',
  tutorAskTopic: 'Was möchtest du heute üben?',
  tutorHelloTopic: 'Hallo {name}! Was möchtest du heute üben?',
  tutorCodeOk: 'Danke, der Code stimmt! Was möchtest du heute üben?',
  tutorCodeChanged: 'Der Klassen-Code stimmt nicht mehr. Wie lautet euer Klassen-Code?',
  tutorCodeThanks: 'Danke! Schick mir deine letzte Nachricht bitte nochmal.',
  tutorWelcomeBack: 'Willkommen zurück, {name}! Was üben wir heute?',
  tutorLastTime: 'Letztes Mal: {topic} ({score}).',
  tutorResume: 'Willkommen zurück, {name}! Wir machen da weiter, wo du aufgehört hast.',
  tutorAskTopicAgain: 'Gern! Was möchtest du jetzt üben?',
  tutorChooseGrammar: 'Welches Grammatik-Thema möchtest du üben?',
  tutorChooseVocab: 'Welchen Wortschatz möchtest du üben?',
  tutorNoTopicsForLevel: 'Für {level} gibt es noch keine eigenen Lektionen. Hier sind alle Themen – ich passe die Sprache an dein Niveau an.',
  tutorNoTopicsOfType: 'Dazu gibt es noch keine Lektion. Wähle ein anderes Thema oder schreib mir, was du üben möchtest.',
  tutorRestart: 'Neue Runde, {name}! Was möchtest du üben?',
  tutorStopped: 'Okay, wir hören hier auf. Gut gemacht, {name}!',
  tutorFinishedByCount: 'Okay, {n} Fragen – die hast du schon geschafft. Gut gemacht!',
  tutorStopIdle: 'Okay! Wenn du wieder üben möchtest, wähl einfach ein Thema.',
  tutorStopNoAnswers: 'Okay, wir hören auf. Wenn du wieder üben möchtest, wähl einfach ein Thema.',
  tutorAlreadyFinished: 'Diese Runde ist schon fertig. Tippe «{again}» oder wähle ein neues Thema.',
  tutorAlreadyOnTopic: 'Du übst gerade schon «{topic}». Mach einfach weiter – oder wähle ein anderes Thema.',
  tutorStartTopic: 'Starte bitte das Thema «{topic}».',
};

const en = {
  ...tutor,
  // header
  brand: 'wort.',
  tagline: 'Your German, one conversation at a time.',
  streak: '{n}-day streak',
  hello: 'Hallo, {name}',
  accountMenu: 'Account menu',
  menuNewSession: 'Start a new session',
  menuChangeName: 'Change name',
  confirmChangeName: 'Start again with a different name? Your progress on this device will be kept.',

  // chat
  chatTitle: "Let's talk German.",
  chatSubtitle: 'Pick a topic, change your level, or ask for help. Just say it here.',
  statusStarting: 'Getting started',
  statusChoosing: 'Choosing a topic',
  statusFlashcards: 'Flashcards in progress',
  statusLesson: 'Lesson in progress',
  statusFinished: 'Session complete',
  today: 'Today',
  you: 'You',
  tutorName: 'wort.',
  tutorRole: 'Your German tutor',
  questionOf: 'Question {n} of {total}',
  cardOf: 'Card {n} of {total}',
  feedbackSpotOn: 'Spot on',
  feedbackPolish: 'A little polish',
  feedbackFix: "Let's fix this",
  feedbackNotQuite: 'Not quite',
  summaryTitle: 'Session complete',
  summaryEnded: 'Session ended',
  summaryScore: '{correct} of {answered} correct',
  summaryDetail: '{done} of {total} questions',
  summarySkipped: '{n} skipped',
  inputLabel: 'Your message',
  inputPlaceholder: "Reply in German, or tell wort. what you'd like to do …",
  inputPlaceholderName: 'Type your name …',
  inputPlaceholderCode: 'Type the class code …',
  send: 'Send',
  composerNote: 'Your conversation is the control panel. Everything updates as you chat.',
  enterToSend: 'Enter to send ↵',
  typing: 'wort. is writing …',
  typingSlow: 'Still thinking – the tutor is a bit slow right now …',
  retry: 'Try again',
  errorNetwork: 'No connection to the server. Check your internet and try again.',
  errorUnexpected: 'The server sent an unexpected answer ({status}). Please try again.',
  errorTimeout: 'The tutor took too long to answer. Please try again.',
  errorInterrupted: 'The page was closed before the tutor answered your last message.',
  codeHidden: '••••••',

  // "You can say" panel
  optionsTitle: 'You can say',
  optionsHide: 'Hide options',
  optionsShow: 'Show options',
  optionsTab: 'Options',
  groupNow: 'Right now',
  groupNext: 'What next?',
  groupPractising: 'While practising',
  groupFlashcards: 'Flashcards',
  groupTopics: 'Topics for {level}',
  groupTopicsAll: 'All topics',
  groupTopic: 'Topic',
  optionsFootnote: 'Tap one, or just type it in the chat.',
  optionsOnboarding: 'Answer wort. in the chat to get started. The options appear here.',
  chipHint: 'Give me a hint',
  chipRule: 'Explain the rule',
  chipSkip: 'Skip this one',
  chipRepeat: 'Repeat my mistakes',
  chipEndSession: 'End session',
  chipAgain: 'Same topic again',
  chipGrammar: 'Grammar',
  chipVocab: 'Vocabulary',
  chipChangeTopic: 'Change topic',
  chipEnDe: 'English → German',
  chipDeEn: 'German → English',
  chipMixed: 'Mixed',
  chipSentencesOn: 'Add sentences',
  chipSentencesOff: 'Words only',

  // right panel: settings
  panelTitle: 'Your session',
  level: 'Level',
  difficulty: 'Difficulty',
  diff_easy: 'Easy',
  diff_medium: 'Medium',
  diff_hard: 'Hard',
  diffHelp_easy: 'Hints in brackets, multiple choice allowed, short answers.',
  diffHelp_medium: 'A small hint under each question, no case hint.',
  diffHelp_hard: 'No hints. Full sentences; flashcards also ask for the plural.',
  questions: 'Questions per session',
  flashcards: 'Flashcards',
  dir_en_de: 'English → German',
  dir_de_en: 'German → English',
  dir_mixed: 'Mixed',
  dirShort_en_de: 'EN → DE',
  dirShort_de_en: 'DE → EN',
  dirShort_mixed: 'Mixed',
  sentencesToggle: 'Add sentences (article + adjective)',
  refLang: 'Reference language: English',
  topic: 'Topic',
  mode: 'Mode',
  modeExercises: 'Exercises',
  withSentences: '+ sentences',
  notChosen: 'Not chosen yet',
  settingsNote: 'The topic is chosen in the chat.',
  type_Grammatik: 'Grammar',
  type_Wortschatz: 'Vocabulary',
  type_Gemischt: 'Mixed',
  type_free: 'Free practice',
  ex_flashcard: 'flashcard',
  ex_gapfill: 'gap fill',
  ex_noundrill: 'noun drill',
  ex_translation: 'translation',
  ex_choice: 'multiple choice',
  ex_build: 'sentence building',
  ex_findmistake: 'find the mistake',

  // right panel: views
  views: 'Views',
  view_glance: 'At a glance',
  view_progress: 'Progress & gaps',
  view_grammar: 'Grammar focus',
  panelHint: 'You can also change all of this in the chat, e.g. «make it harder», «20 questions» or «stop».',

  // at a glance
  currentLesson: 'Current lesson',
  synced: 'Synced with chat',
  levelName_A1: 'Beginner',
  levelName_A2: 'Elementary',
  levelName_B1: 'Intermediate',
  levelCaption: 'Your study level · CEFR',
  topicEmpty: 'Your topic appears here once you pick one in the chat.',
  grammarFocusLine: 'Grammar focus: {rule}',
  howYoureDoing: "How you're doing",
  headline_none: "Let's begin.",
  headline_perfect: 'Perfect so far.',
  headline_strong: 'Going strong.',
  headline_good: 'A good start.',
  headline_keep: 'Keep at it.',
  basedOnOne: 'Based on your last answer',
  basedOnMany: 'Based on your last {n} answers',
  basedOnNone: 'Answer the first question to see your score',
  correctLabel: 'correct',
  onTarget: 'On target',
  keepPractising: 'Keep practising',
  lessonProgress: 'Session progress',
  questionsOf: '{n} of {total} questions',
  recentSessions: 'Last sessions',

  // progress & gaps
  gapTitle: 'Gap from this conversation',
  yourAnswer: 'Your answer',
  corrected: 'Corrected',
  noGapTitle: 'No gaps so far',
  noGapText: 'When something goes wrong, the rule behind it shows up here – with your answer and the correction.',
  yourAnswers: 'Your answers',
  scoreCorrect: '{correct}/{answered} correct',
  youWrote: '(you: {words})',
  skipped: 'skipped',
  noAnswers: 'Every answer you give appears here, with the correction.',

  // grammar focus
  grammarFocus: 'Grammar focus',
  fromConversation: 'From your conversation',
  watchOut: 'Watch out',
  noGrammar: 'The rule of your topic appears here once you start. You can also say «Explain the rule».',

  // short lines in the chat when a setting changes
  sysLevel: 'Level: {value}',
  sysDifficulty: 'Difficulty: {value}',
  sysView: 'View: {value}',
  sysTopic: 'Topic: {value}',
  sysQuestions: 'Questions per session: {value}',
  sysDirection: 'Flashcards: {value}',
  sysSentencesOn: 'Sentences with the word: on',
  sysSentencesOff: 'Sentences with the word: off',
  sysPrevSession: 'Previous session: {correct}/{answered} correct',
  sysCancelled: 'Stopped waiting for the tutor',
  cancel: 'Stop waiting',
};

const de = {
  ...tutor,
  brand: 'wort.',
  tagline: 'Dein Deutsch, ein Gespräch nach dem anderen.',
  streak: '{n} Tage in Folge',
  hello: 'Hallo, {name}',
  accountMenu: 'Konto-Menü',
  menuNewSession: 'Neue Sitzung starten',
  menuChangeName: 'Namen ändern',
  confirmChangeName: 'Mit einem anderen Namen neu beginnen? Dein Fortschritt auf diesem Gerät bleibt gespeichert.',

  chatTitle: 'Lass uns Deutsch reden.',
  chatSubtitle: 'Wähle ein Thema, ändere dein Niveau oder frag nach Hilfe. Schreib es einfach hier.',
  statusStarting: 'Los geht’s',
  statusChoosing: 'Thema wählen',
  statusFlashcards: 'Karteikarten laufen',
  statusLesson: 'Lektion läuft',
  statusFinished: 'Sitzung beendet',
  today: 'Heute',
  you: 'Du',
  tutorName: 'wort.',
  tutorRole: 'Dein Deutsch-Tutor',
  questionOf: 'Frage {n} von {total}',
  cardOf: 'Karte {n} von {total}',
  feedbackSpotOn: 'Genau richtig',
  feedbackPolish: 'Ein kleiner Schliff',
  feedbackFix: 'Das korrigieren wir',
  feedbackNotQuite: 'Noch nicht ganz',
  summaryTitle: 'Runde geschafft',
  summaryEnded: 'Sitzung beendet',
  summaryScore: '{correct} von {answered} richtig',
  summaryDetail: '{done} von {total} Fragen',
  summarySkipped: '{n} übersprungen',
  inputLabel: 'Deine Nachricht',
  inputPlaceholder: 'Antworte auf Deutsch oder sag wort., was du machen möchtest …',
  inputPlaceholderName: 'Schreib deinen Namen …',
  inputPlaceholderCode: 'Schreib den Klassen-Code …',
  send: 'Senden',
  composerNote: 'Dein Gespräch ist die Steuerung. Alles passt sich an, während du schreibst.',
  enterToSend: 'Enter zum Senden ↵',
  typing: 'wort. schreibt …',
  typingSlow: 'Einen Moment noch – der Tutor ist gerade etwas langsam …',
  retry: 'Nochmal versuchen',
  errorNetwork: 'Keine Verbindung zum Server. Prüfe dein Internet und versuch es nochmal.',
  errorUnexpected: 'Unerwartete Antwort vom Server ({status}). Bitte versuch es nochmal.',
  errorTimeout: 'Der Tutor hat zu lange gebraucht. Bitte versuch es nochmal.',
  errorInterrupted: 'Die Seite wurde geschlossen, bevor der Tutor auf deine letzte Nachricht geantwortet hat.',
  codeHidden: '••••••',

  optionsTitle: 'Du kannst sagen',
  optionsHide: 'Optionen ausblenden',
  optionsShow: 'Optionen einblenden',
  optionsTab: 'Optionen',
  groupNow: 'Gerade jetzt',
  groupNext: 'Wie weiter?',
  groupPractising: 'Beim Üben',
  groupFlashcards: 'Karteikarten',
  groupTopics: 'Themen für {level}',
  groupTopicsAll: 'Alle Themen',
  groupTopic: 'Thema',
  optionsFootnote: 'Tippe eine Option an oder schreib sie einfach in den Chat.',
  optionsOnboarding: 'Antworte wort. im Chat, um zu starten. Die Optionen erscheinen hier.',
  chipHint: 'Gib mir einen Tipp',
  chipRule: 'Erklär die Regel',
  chipSkip: 'Überspringen',
  chipRepeat: 'Wiederhole meine Fehler',
  chipEndSession: 'Sitzung beenden',
  chipAgain: 'Gleiches Thema nochmal',
  chipGrammar: 'Grammatik',
  chipVocab: 'Wortschatz',
  chipChangeTopic: 'Anderes Thema',
  chipEnDe: 'Englisch → Deutsch',
  chipDeEn: 'Deutsch → Englisch',
  chipMixed: 'Gemischt',
  chipSentencesOn: 'Mit Sätzen',
  chipSentencesOff: 'Nur Wörter',

  panelTitle: 'Deine Sitzung',
  level: 'Niveau',
  difficulty: 'Schwierigkeit',
  diff_easy: 'Leicht',
  diff_medium: 'Mittel',
  diff_hard: 'Schwer',
  diffHelp_easy: 'Tipps in Klammern, Auswahlantworten erlaubt, kurze Antworten.',
  diffHelp_medium: 'Ein kleiner Tipp unter jeder Frage, kein Hinweis auf den Kasus.',
  diffHelp_hard: 'Keine Tipps. Ganze Sätze; Karteikarten fragen auch nach dem Plural.',
  questions: 'Fragen pro Sitzung',
  flashcards: 'Karteikarten',
  dir_en_de: 'Englisch → Deutsch',
  dir_de_en: 'Deutsch → Englisch',
  dir_mixed: 'Gemischt',
  dirShort_en_de: 'EN → DE',
  dirShort_de_en: 'DE → EN',
  dirShort_mixed: 'Gemischt',
  sentencesToggle: 'Mit Sätzen (Artikel + Adjektiv)',
  refLang: 'Referenzsprache: Englisch',
  topic: 'Thema',
  mode: 'Modus',
  modeExercises: 'Übungen',
  withSentences: '+ Sätze',
  notChosen: 'Noch nicht gewählt',
  settingsNote: 'Das Thema wählst du im Chat.',
  type_Grammatik: 'Grammatik',
  type_Wortschatz: 'Wortschatz',
  type_Gemischt: 'Gemischt',
  type_free: 'Freies Üben',
  ex_flashcard: 'Karteikarte',
  ex_gapfill: 'Lückentext',
  ex_noundrill: 'Nomen-Drill',
  ex_translation: 'Übersetzung',
  ex_choice: 'Auswahl',
  ex_build: 'Satzbau',
  ex_findmistake: 'Fehler finden',

  views: 'Ansichten',
  view_glance: 'Überblick',
  view_progress: 'Fortschritt & Lücken',
  view_grammar: 'Grammatik-Fokus',
  panelHint: 'Du kannst all das auch im Chat ändern, z. B. «schwieriger», «20 Fragen» oder «Stopp».',

  currentLesson: 'Aktuelle Lektion',
  synced: 'Mit dem Chat verbunden',
  levelName_A1: 'Anfänger',
  levelName_A2: 'Grundstufe',
  levelName_B1: 'Mittelstufe',
  levelCaption: 'Dein Niveau · GER',
  topicEmpty: 'Dein Thema erscheint hier, sobald du es im Chat wählst.',
  grammarFocusLine: 'Grammatik-Fokus: {rule}',
  howYoureDoing: 'So läuft es',
  headline_none: 'Los geht’s.',
  headline_perfect: 'Bisher perfekt.',
  headline_strong: 'Sehr stark.',
  headline_good: 'Ein guter Anfang.',
  headline_keep: 'Dranbleiben!',
  basedOnOne: 'Nach deiner letzten Antwort',
  basedOnMany: 'Nach deinen letzten {n} Antworten',
  basedOnNone: 'Beantworte die erste Frage, dann siehst du dein Ergebnis',
  correctLabel: 'richtig',
  onTarget: 'Sitzt',
  keepPractising: 'Weiter üben',
  lessonProgress: 'Fortschritt der Sitzung',
  questionsOf: '{n} von {total} Fragen',
  recentSessions: 'Letzte Sitzungen',

  gapTitle: 'Lücke aus diesem Gespräch',
  yourAnswer: 'Deine Antwort',
  corrected: 'Korrigiert',
  noGapTitle: 'Bisher keine Lücken',
  noGapText: 'Wenn etwas nicht stimmt, erscheint hier die Regel dazu – mit deiner Antwort und der Korrektur.',
  yourAnswers: 'Deine Antworten',
  scoreCorrect: '{correct}/{answered} richtig',
  youWrote: '(du: {words})',
  skipped: 'übersprungen',
  noAnswers: 'Jede Antwort erscheint hier, mit der Korrektur.',

  grammarFocus: 'Grammatik-Fokus',
  fromConversation: 'Aus deinem Gespräch',
  watchOut: 'Achtung',
  noGrammar: 'Die Regel deines Themas erscheint hier, sobald du startest. Du kannst auch «Erklär die Regel» sagen.',

  sysLevel: 'Niveau: {value}',
  sysDifficulty: 'Schwierigkeit: {value}',
  sysView: 'Ansicht: {value}',
  sysTopic: 'Thema: {value}',
  sysQuestions: 'Fragen pro Sitzung: {value}',
  sysDirection: 'Karteikarten: {value}',
  sysSentencesOn: 'Sätze mit dem Wort: an',
  sysSentencesOff: 'Sätze mit dem Wort: aus',
  sysPrevSession: 'Letzte Sitzung: {correct}/{answered} richtig',
  sysCancelled: 'Warten abgebrochen',
  cancel: 'Warten abbrechen',
};

const SETS = { en, de };

export function t(key, vars) {
  const text = SETS[UI_LANG]?.[key] ?? en[key] ?? key;
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (m, k) => (vars[k] ?? m));
}

// 'en-de' → 'en_de' (keys can't contain "-" comfortably)
export const dirKey = (d) => String(d || 'en-de').replace('-', '_');
